version: "3"

tasks:
  run:
    cmds:
      - echo "server starting..."
      - go run cmd/main.go
    silent: true

  run-redis:
    cmds:
      - echo "server starting with redis..."
      - go run cmd/main.go --db=redis
    silent: true
